export const apiConstants = {
  GET_ALL_VIDEOS: "/api/videos",
  GET_ALL_CATEGORIES: "/api/categories",
  GET_SINGLE_VIDEO: "/api/video",
  LIKE_VIDEO: "/api/user/likes",
  REMOVE_LIKED_VIDEO: "/api/user/likes",
  ADD_TO_WATCH_LATER: "/api/user/watchlater",
  REMOVE_FROM_WATCH_LATER: "/api/user/watchlater",
  WATCH_LATER_VIDEOS: "/api/user/watchlater",
  ADD_PLAYLIST: "/api/user/playlists",
  REMOVE_PLAYLIST: "/api/user/playlists",
  GET_ALL_PLAYLIST: "/api/user/playlists",
  ADD_VIDEO_TO_PLAYLIST: "/api/user/playlists",
  REMOVE_VIDEO_FROM_PLAYLIST: "/api/user/playlists",
  GET_ALL_PLAYLIST_VIDEOS: "/api/user/playlists",
};
